const questions = [
  // ==========================================
  // 1. KEY CONCEPTS OF SERVICE MANAGEMENT (1-20)
  // ==========================================
  {
    id: 1,
    category: "1. KEY CONCEPTS",
    question: "What term describes the functionality offered by a product or service to meet a particular need (fit for purpose)?",
    options: ["Warranty", "Utility", "Outcome", "Output"],
    correct: 1,
    explanation: "Utility is the functionality offered by a product or service to meet a particular need ('fit for purpose')."
  },
  {
    id: 2,
    category: "1. KEY CONCEPTS",
    question: "Which concept refers to the assurance that a product or service will meet agreed requirements (fit for use)?",
    options: ["Utility", "Warranty", "Risk", "Cost"],
    correct: 1,
    explanation: "Warranty provides assurance regarding availability, capacity, security, and continuity ('fit for use')."
  },
  {
    id: 3,
    category: "1. KEY CONCEPTS",
    question: "What is defined as a result for a stakeholder enabled by one or more outputs?",
    options: ["Outcome", "Output", "Service offering", "Asset"],
    correct: 0,
    explanation: "An outcome is the result for a stakeholder enabled by one or more outputs (e.g., increased sales enabled by a new CRM system)."
  },
  {
    id: 4,
    category: "1. KEY CONCEPTS",
    question: "What is a tangible or intangible deliverable produced by an activity?",
    options: ["Outcome", "Output", "Value", "Utility"],
    correct: 1,
    explanation: "An output is a deliverable (such as a report, software release, or installed server) created by an activity."
  },
  {
    id: 5,
    category: "1. KEY CONCEPTS",
    question: "In ITIL 4, how is 'Value' best defined?",
    options: [
      "The financial profit generated by an IT department",
      "The perceived benefits, usefulness, and importance of something",
      "The total reduction of operational overhead",
      "The completion of all agreed project milestones"
    ],
    correct: 1,
    explanation: "Value is co-created and defined as the perceived benefits, usefulness, and importance of something to stakeholders."
  },
  {
    id: 6,
    category: "1. KEY CONCEPTS",
    question: "Which role defines the requirements for a service and takes responsibility for the outcomes of service consumption?",
    options: ["User", "Customer", "Sponsor", "Supplier"],
    correct: 1,
    explanation: "The customer defines the service requirements and takes responsibility for the outcomes of service consumption."
  },
  {
    id: 7,
    category: "1. KEY CONCEPTS",
    question: "Which role authorizes the budget for service consumption?",
    options: ["User", "Customer", "Sponsor", "Service Provider"],
    correct: 2,
    explanation: "The sponsor is the person or group who authorizes the budget for service consumption."
  },
  {
    id: 8,
    category: "1. KEY CONCEPTS",
    question: "Which role actually uses the day-to-day IT services?",
    options: ["Sponsor", "Customer", "User", "Partner"],
    correct: 2,
    explanation: "A user is a person who uses services on a daily basis."
  },
  {
    id: 9,
    category: "1. KEY CONCEPTS",
    question: "What is a formal description of one or more services designed to address the needs of a target consumer group?",
    options: ["Service Level Agreement", "Service Offering", "Service Action", "Service Model"],
    correct: 1,
    explanation: "A service offering combines goods, access to resources, and service actions tailored to specific consumer needs."
  },
  {
    id: 10,
    category: "1. KEY CONCEPTS",
    question: "Which component of a service offering involves transferring ownership of a physical asset to the consumer?",
    options: ["Goods", "Access to resources", "Service actions", "Utility"],
    correct: 0,
    explanation: "Goods involve transferring ownership (e.g., delivering a mobile device or laptop to a user)."
  },
  {
    id: 11,
    category: "1. KEY CONCEPTS",
    question: "Which component of a service offering gives the consumer permission to use a system without transferring ownership?",
    options: ["Goods", "Access to resources", "Service actions", "Warranty"],
    correct: 1,
    explanation: "Access to resources allows consumers to use assets (like cloud storage or network access) governed by terms and conditions."
  },
  {
    id: 12,
    category: "1. KEY CONCEPTS",
    question: "Which component of a service offering includes activities performed by the service provider to address a consumer's needs?",
    options: ["Goods", "Access to resources", "Service actions", "Outcomes"],
    correct: 2,
    explanation: "Service actions are performed by provider personnel (e.g., user support, system maintenance)."
  },
  {
    id: 13,
    category: "1. KEY CONCEPTS",
    question: "How do service providers and consumers collaborate to generate value?",
    options: ["Through Value Isolation", "Through Value Co-creation", "Through One-way Delivery", "Through Contractual Mandates"],
    correct: 1,
    explanation: "ITIL 4 emphasizes that value is not simply delivered by the provider, but co-created through active collaboration."
  },
  {
    id: 14,
    category: "1. KEY CONCEPTS",
    question: "What term refers to the possible events that could cause harm, loss, or make it harder to achieve objectives?",
    options: ["Cost", "Risk", "Output", "Sponsor"],
    correct: 1,
    explanation: "Risk is defined as a possible event that could cause harm or loss, or make it more difficult to achieve objectives."
  },
  {
    id: 15,
    category: "1. KEY CONCEPTS",
    question: "From a service consumer's perspective, service management aims to reduce which two elements?",
    options: ["Utility and Warranty", "Costs and Risks", "Outputs and Outcomes", "Goods and Service Actions"],
    correct: 1,
    explanation: "Services remove or reduce specific costs and risks for the consumer while adding utility and warranty."
  },
  {
    id: 16,
    category: "1. KEY CONCEPTS",
    question: "What is the term for joint activities performed by a service provider and a service consumer to ensure continual value co-creation?",
    options: ["Service Provision", "Service Consumption", "Service Relationship Management", "Service Architecture"],
    correct: 2,
    explanation: "Service Relationship Management encompasses service provision, consumption, and co-creation activities."
  },
  {
    id: 17,
    category: "1. KEY CONCEPTS",
    question: "Which statement about costs in service management is TRUE?",
    options: [
      "Services introduce new costs while removing existing ones",
      "Services completely eliminate all consumer financial obligations",
      "Costs are evaluated only during service design",
      "Costs are synonymous with service outcomes"
    ],
    correct: 0,
    explanation: "Services impose some costs on consumers (e.g., subscription fees, training) while removing others (e.g., hardware infrastructure maintenance)."
  },
  {
    id: 18,
    category: "1. KEY CONCEPTS",
    question: "What is an organization?",
    options: [
      "A legally registered corporate body only",
      "A person or group of people that has its own functions with responsibilities, authorities, and relationships to achieve objectives",
      "A group of IT professionals delivering software solutions",
      "An external vendor providing technical hardware"
    ],
    correct: 1,
    explanation: "An organization is a person or group with its own functions, responsibilities, authorities, and relationships to achieve objectives."
  },
  {
    id: 19,
    category: "1. KEY CONCEPTS",
    question: "Which of the following is required for a service to create value?",
    options: ["Utility only", "Warranty only", "Both Utility and Warranty", "Neither Utility nor Warranty"],
    correct: 2,
    explanation: "A service must provide both utility (fit for purpose) AND warranty (fit for use) to effectively create value."
  },
  {
    id: 20,
    category: "1. KEY CONCEPTS",
    question: "What are management activities performed by an organization to supply services called?",
    options: ["Service Provision", "Service Consumption", "Service Relationship", "Service Offering"],
    correct: 0,
    explanation: "Service provision includes managing provider resources, supplying access to resources, and executing service actions."
  },

  // ==========================================
  // 2. THE 7 ITIL GUIDING PRINCIPLES (21-40)
  // ==========================================
  {
    id: 21,
    category: "2. GUIDING PRINCIPLES",
    question: "Which guiding principle states that everything an organization does should link back to value for its stakeholders?",
    options: ["Start where you are", "Focus on value", "Keep it simple and practical", "Optimize and automate"],
    correct: 1,
    explanation: "'Focus on value' requires knowing who the customer is and how they define value in every situation."
  },
  {
    id: 22,
    category: "2. GUIDING PRINCIPLES",
    question: "Which guiding principle advises against starting from scratch without assessing existing practices and assets?",
    options: ["Start where you are", "Focus on value", "Think and work holistically", "Progress iteratively with feedback"],
    correct: 0,
    explanation: "'Start where you are' encourages evaluating current services, processes, and tools before building something new."
  },
  {
    id: 23,
    category: "2. GUIDING PRINCIPLES",
    question: "Organizing work into smaller, manageable sections that can be executed and evaluated quickly aligns with which principle?",
    options: ["Collaborate and promote visibility", "Progress iteratively with feedback", "Keep it simple and practical", "Optimize and automate"],
    correct: 1,
    explanation: "'Progress iteratively with feedback' advocates breaking large initiatives into smaller iterations using feedback loops."
  },
  {
    id: 24,
    category: "2. GUIDING PRINCIPLES",
    question: "Which guiding principle emphasizes working together across boundaries and sharing information openly?",
    options: ["Collaborate and promote visibility", "Think and work holistically", "Focus on value", "Start where you are"],
    correct: 0,
    explanation: "'Collaborate and promote visibility' breaks down organizational silos and builds trust through transparency."
  },
  {
    id: 25,
    category: "2. GUIDING PRINCIPLES",
    question: "Which principle stresses that no service, process, or department stands alone, and all parts must work together as a whole?",
    options: ["Optimize and automate", "Progress iteratively with feedback", "Think and work holistically", "Focus on value"],
    correct: 2,
    explanation: "'Think and work holistically' requires an end-to-end understanding of how all components interact to deliver value."
  },
  {
    id: 26,
    category: "2. GUIDING PRINCIPLES",
    question: "Eliminating unnecessary steps and using the minimum number of steps to achieve an outcome reflects which principle?",
    options: ["Keep it simple and practical", "Optimize and automate", "Start where you are", "Collaborate and promote visibility"],
    correct: 0,
    explanation: "'Keep it simple and practical' advises removing steps that do not directly create value or satisfy compliance."
  },
  {
    id: 27,
    category: "2. GUIDING PRINCIPLES",
    question: "Before a process can be effectively automated, what step should be taken according to ITIL principles?",
    options: ["It should be fully documented", "It should be optimized", "It should be outsourced", "It should be expanded"],
    correct: 1,
    explanation: "Under 'Optimize and automate', technology should only be applied after a workflow has been streamlined and optimized."
  },
  {
    id: 28,
    category: "2. GUIDING PRINCIPLES",
    question: "What tool or technique helps collect responses before, during, and after an iteration to refine future work?",
    options: ["Baseline measurement", "Feedback loop", "Service level agreement", "Change register"],
    correct: 1,
    explanation: "Feedback loops allow teams to gather input and adjust continuous improvements dynamically."
  },
  {
    id: 29,
    category: "2. GUIDING PRINCIPLES",
    question: "When applying 'Start where you are', how should data about current performance ideally be gathered?",
    options: [
      "Solely from historic reports provided by management",
      "Through direct observation combined with objective metrics",
      "By replacing old tools before measuring performance",
      "By conducting opinion surveys across all departments"
    ],
    correct: 1,
    explanation: "Direct observation (going to see for yourself) combined with real metrics is essential when assessing current state."
  },
  {
    id: 30,
    category: "2. GUIDING PRINCIPLES",
    question: "Which guiding principle is most helpful when trying to eliminate 'silo mentality' within teams?",
    options: ["Keep it simple and practical", "Collaborate and promote visibility", "Start where you are", "Optimize and automate"],
    correct: 1,
    explanation: "Collaboration and visibility prevent teams from working in isolation and encourage shared goal alignment."
  },
  {
    id: 31,
    category: "2. GUIDING PRINCIPLES",
    question: "What is a key risk of failing to 'Think and work holistically'?",
    options: [
      "Changes in one area may cause unexpected negative consequences elsewhere",
      "Automation might cost more than expected",
      "Feedback loops will become too frequent",
      "Existing services will be needlessly duplicated"
    ],
    correct: 0,
    explanation: "Focusing on isolated parts without holistic thinking leads to sub-optimization and unintended operational disruption."
  },
  {
    id: 32,
    category: "2. GUIDING PRINCIPLES",
    question: "Which rule helps enforce 'Keep it simple and practical' when designing processes?",
    options: [
      "Include controls for every theoretical exception",
      "Focus on the main scenarios and add complexity only when required",
      "Automate every manual step immediately",
      "Rely exclusively on external vendor templates"
    ],
    correct: 1,
    explanation: "Design for the primary, common use cases first; avoid adding controls for rare edge cases unless strictly necessary."
  },
  {
    id: 33,
    category: "2. GUIDING PRINCIPLES",
    question: "How do the 7 Guiding Principles interact with each other?",
    options: [
      "They are applied in a strict sequential order from 1 to 7",
      "Organizations choose only one principle per project",
      "They are universally applicable and complement one another",
      "They replace the need for governance models"
    ],
    correct: 2,
    explanation: "The guiding principles are non-sequential, universal, and designed to be integrated together depending on context."
  },
  {
    id: 34,
    category: "2. GUIDING PRINCIPLES",
    question: "In the principle 'Focus on value', who ultimately determines what value is?",
    options: ["The IT Infrastructure Team", "The Service Consumer", "The Software Developer", "The External Auditor"],
    correct: 1,
    explanation: "Value is subjective and defined entirely by the consumer or stakeholder receiving the service outcomes."
  },
  {
    id: 35,
    category: "2. GUIDING PRINCIPLES",
    question: "Using a Minimum Viable Product (MVP) to test ideas early aligns with which principle?",
    options: ["Progress iteratively with feedback", "Start where you are", "Optimize and automate", "Keep it simple and practical"],
    correct: 0,
    explanation: "An MVP provides a fast, workable sample to gather early feedback during iterative development."
  },
  {
    id: 36,
    category: "2. GUIDING PRINCIPLES",
    question: "What does the principle 'Optimize and automate' say about human intervention?",
    options: [
      "Humans should oversee every routine decision",
      "Automation should replace human decisions wherever repetitive, predictable work exists",
      "Human intervention is superior to automated workflows in all cases",
      "Automation should precede optimization"
    ],
    correct: 1,
    explanation: "Standard, predictable tasks should be automated so human effort can focus on complex tasks and decision-making."
  },
  {
    id: 37,
    category: "2. GUIDING PRINCIPLES",
    question: "If an existing service process works reasonably well, what does 'Start where you are' suggest doing?",
    options: [
      "Scrap it and build a modern platform",
      "Re-use and tweak elements that are working while fixing deficiencies",
      "Freeze all changes indefinitely",
      "Outsource the entire function"
    ],
    correct: 1,
    explanation: "Assess current functional elements, preserve what works, and alter only what is necessary."
  },
  {
    id: 38,
    category: "2. GUIDING PRINCIPLES",
    question: "Promoting visibility of work helps prevent which problem?",
    options: [
      "Excessive network bandwidth consumption",
      "People working on conflicting priorities or duplicate efforts",
      "High software licensing fees",
      "Hardware component failure"
    ],
    correct: 1,
    explanation: "Making work visible ensures everyone understands operational priorities and prevents duplicated or conflicting efforts."
  },
  {
    id: 39,
    category: "2. GUIDING PRINCIPLES",
    question: "Applying the Pareto Principle (the 80/20 rule) to simplify processes aligns best with which principle?",
    options: ["Focus on value", "Keep it simple and practical", "Start where you are", "Think and work holistically"],
    correct: 1,
    explanation: "Focusing on the 20% of effort that yields 80% of value keeps processes simple, practical, and effective."
  },
  {
    id: 40,
    category: "2. GUIDING PRINCIPLES",
    question: "What is the primary focus when identifying stakeholders for 'Collaborate and promote visibility'?",
    options: [
      "Only C-level executives",
      "Internal IT developers exclusively",
      "Anyone who has an interest or is affected by the service",
      "External regulators only"
    ],
    correct: 2,
    explanation: "Stakeholders include customers, users, internal teams, suppliers, and anyone impacted by service delivery."
  },

  // ==========================================
  // 3. THE FOUR DIMENSIONS OF SERVICE MANAGEMENT (41-55)
  // ==========================================
  {
    id: 41,
    category: "3. FOUR DIMENSIONS",
    question: "Which of the Four Dimensions covers roles, responsibilities, culture, and communication structures?",
    options: ["Organizations and People", "Information and Technology", "Partners and Suppliers", "Value Streams and Processes"],
    correct: 0,
    explanation: "Organizations and People focuses on formal structures, roles, leadership, corporate culture, and skills."
  },
  {
    id: 42,
    category: "3. FOUR DIMENSIONS",
    question: "Which dimension addresses workflow efficiency, activities, and how inputs transform into value outputs?",
    options: ["Organizations and People", "Information and Technology", "Partners and Suppliers", "Value Streams and Processes"],
    correct: 3,
    explanation: "Value Streams and Processes defines the steps, workflows, activities, and procedures necessary to deliver services."
  },
  {
    id: 43,
    category: "3. FOUR DIMENSIONS",
    question: "Which dimension deals with vendor contracts, third-party relationships, and sourcing strategies?",
    options: ["Organizations and People", "Information and Technology", "Partners and Suppliers", "Value Streams and Processes"],
    correct: 2,
    explanation: "Partners and Suppliers encompasses contracts, relationship management, and third-party vendors."
  },
  {
    id: 44,
    category: "3. FOUR DIMENSIONS",
    question: "Which dimension encompasses databases, knowledge bases, security systems, and infrastructure tools?",
    options: ["Organizations and People", "Information and Technology", "Partners and Suppliers", "Value Streams and Processes"],
    correct: 1,
    explanation: "Information and Technology includes technical architecture, applications, data management, and security."
  },
  {
    id: 45,
    category: "3. FOUR DIMENSIONS",
    question: "Factors such as political shifts, economic changes, and legal regulations (PESTLE) influence what aspect of ITIL?",
    options: [
      "Only the Incident Management practice",
      "The Four Dimensions of Service Management",
      "The layout of the Service Desk",
      "Standard change approval thresholds"
    ],
    correct: 1,
    explanation: "External PESTLE factors (Political, Economic, Social, Technological, Legal, Environmental) influence all Four Dimensions."
  },
  {
    id: 46,
    category: "3. FOUR DIMENSIONS",
    question: "What is a value stream?",
    options: [
      "A set of contractual agreements with external vendors",
      "A series of steps an organization undertakes to create and deliver a product or service",
      "A database storing configuration item records",
      "A list of open incidents prioritized by impact"
    ],
    correct: 1,
    explanation: "A value stream is a specific combination of activities that transforms inputs into valuable outputs for users."
  },
  {
    id: 47,
    category: "3. FOUR DIMENSIONS",
    question: "Which framework or approach helps organizations manage multi-vendor environments within the Partners & Suppliers dimension?",
    options: ["SIAM (Service Integration and Management)", "DevOps", "Agile Software Manifestos", "ITIL Continuous Deployment"],
    correct: 0,
    explanation: "SIAM (Service Integration and Management) coordinate multiple third-party suppliers seamlessly."
  },
  {
    id: 48,
    category: "3. FOUR DIMENSIONS",
    question: "When evaluating Information & Technology, what critical balance must organizations maintain regarding data?",
    options: [
      "Storing all data locally vs storing no data at all",
      "Information accessibility vs security and compliance",
      "Deleting log files daily vs keeping them forever",
      "Automating code deployment vs manual user acceptance testing"
    ],
    correct: 1,
    explanation: "Organizations must balance easy access to knowledge/information against privacy, security, and regulatory compliance."
  },
  {
    id: 49,
    category: "3. FOUR DIMENSIONS",
    question: "A company culture that encourages open communication, continuous learning, and psychological safety belongs in which dimension?",
    options: ["Organizations and People", "Information and Technology", "Partners and Suppliers", "Value Streams and Processes"],
    correct: 0,
    explanation: "Culture, shared values, and leadership style are central to Organizations and People."
  },
  {
    id: 50,
    category: "3. FOUR DIMENSIONS",
    question: "Why is it important to consider all Four Dimensions equally when designing services?",
    options: [
      "Failing to address any single dimension can lead to unworkable or unreliable services",
      "It is required by global ISO compliance standards",
      "It eliminates the need for Continual Improvement",
      "It guarantees that projects will come in under budget"
    ],
    correct: 0,
    explanation: "Neglecting any one dimension (e.g., focusing only on tech while ignoring people or processes) results in service failure."
  },
  {
    id: 51,
    category: "3. FOUR DIMENSIONS",
    question: "Which of the following is a key consideration within the 'Value Streams and Processes' dimension?",
    options: [
      "Determining staff compensation structures",
      "Identifying waste and non-value-adding activities in workflows",
      "Choosing cloud infrastructure providers",
      "Negotiating SLA penalties with vendors"
    ],
    correct: 1,
    explanation: "Value stream mapping identifies inefficient steps and waste in operational workflows."
  },
  {
    id: 52,
    category: "3. FOUR DIMENSIONS",
    question: "Outsourcing a core IT function to a cloud provider heavily shifts focus toward which dimension?",
    options: ["Organizations and People", "Information and Technology", "Partners and Suppliers", "Value Streams and Processes"],
    correct: 2,
    explanation: "Vendor-managed cloud infrastructure relies heavily on the Partners and Suppliers dimension."
  },
  {
    id: 53,
    category: "3. FOUR DIMENSIONS",
    question: "What term describes a repeatable sequence of activities that transforms inputs into outputs?",
    options: ["Practice", "Process", "Value Chain Activity", "Service Level"],
    correct: 1,
    explanation: "A process is a set of interrelated activities that transforms inputs into predefined outputs."
  },
  {
    id: 54,
    category: "3. FOUR DIMENSIONS",
    question: "Technologies such as AI, machine learning, and cloud computing are evaluated primarily under which dimension?",
    options: ["Organizations and People", "Information and Technology", "Partners and Suppliers", "Value Streams and Processes"],
    correct: 1,
    explanation: "Modern technology platforms and tools fall under Information and Technology."
  },
  {
    id: 55,
    category: "3. FOUR DIMENSIONS",
    question: "How do the Four Dimensions apply across the Service Value System (SVS)?",
    options: [
      "They apply to the entire SVS and every service being managed",
      "They apply only to external customer-facing services",
      "They apply exclusively during service transition",
      "They are used only during major incident reviews"
    ],
    correct: 0,
    explanation: "The Four Dimensions apply holistically to all services and the SVS as a whole."
  },

  // ==========================================
  // 4. SERVICE VALUE SYSTEM & VALUE CHAIN (56-70)
  // ==========================================
  {
    id: 56,
    category: "4. SVS & VALUE CHAIN",
    question: "What are the key INPUTS to the ITIL Service Value System (SVS)?",
    options: [
      "Practices and Continual Improvement",
      "Opportunity and Demand",
      "Outputs and Outcomes",
      "Guiding Principles and Governance"
    ],
    correct: 1,
    explanation: "Opportunity and demand are the core inputs that spark value creation within the SVS."
  },
  {
    id: 57,
    category: "4. SVS & VALUE CHAIN",
    question: "What is the primary OUTPUT of the Service Value System?",
    options: ["Outputs", "Value", "Service Offerings", "Service Level Agreements"],
    correct: 1,
    explanation: "The purpose of the SVS is to convert opportunity and demand into valuable outcomes (Value)."
  },
  {
    id: 58,
    category: "4. SVS & VALUE CHAIN",
    question: "Which central component of the SVS represents the operating model for converting demand into value?",
    options: ["Governance", "Service Value Chain", "Continual Improvement Register", "Guiding Principles"],
    correct: 1,
    explanation: "The Service Value Chain (SVC) is the flexible operating model containing six core activities."
  },
  {
    id: 59,
    category: "4. SVS & VALUE CHAIN",
    question: "Which Service Value Chain activity ensures a shared understanding of vision, current status, and direction across all four dimensions?",
    options: ["Plan", "Improve", "Engage", "Obtain/Build"],
    correct: 0,
    explanation: "The purpose of 'Plan' is to ensure a shared understanding of vision, status, and improvement priorities."
  },
  {
    id: 60,
    category: "4. SVS & VALUE CHAIN",
    question: "Which Service Value Chain activity provides a good understanding of stakeholder needs, transparency, and continual engagement?",
    options: ["Plan", "Engage", "Design and Transition", "Deliver and Support"],
    correct: 1,
    explanation: "'Engage' handles all stakeholder interaction, relationship building, and requirements gathering."
  },
  {
    id: 61,
    category: "4. SVS & VALUE CHAIN",
    question: "Which Service Value Chain activity ensures services continually meet stakeholder expectations for quality, cost, and time-to-market?",
    options: ["Design and Transition", "Obtain/Build", "Deliver and Support", "Improve"],
    correct: 0,
    explanation: "'Design and Transition' ensures products/services meet quality, cost, and release requirements."
  },
  {
    id: 62,
    category: "4. SVS & VALUE CHAIN",
    question: "Which Service Value Chain activity ensures component assets are available when and where they are needed?",
    options: ["Plan", "Engage", "Obtain/Build", "Deliver and Support"],
    correct: 2,
    explanation: "'Obtain/Build' acquires or creates service components, software, and infrastructure."
  },
  {
    id: 63,
    category: "4. SVS & VALUE CHAIN",
    question: "Which Service Value Chain activity ensures services are performed according to agreed specifications and expectations?",
    options: ["Deliver and Support", "Design and Transition", "Obtain/Build", "Plan"],
    correct: 0,
    explanation: "'Deliver and Support' handles operational execution, incident response, and user support."
  },
  {
    id: 64,
    category: "4. SVS & VALUE CHAIN",
    question: "Which Service Value Chain activity ensures continuous enhancement of products, services, and practices?",
    options: ["Plan", "Improve", "Engage", "Obtain/Build"],
    correct: 1,
    explanation: "'Improve' drives ongoing optimization across all elements of service management."
  },
  {
    id: 65,
    category: "4. SVS & VALUE CHAIN",
    question: "How do activities in the Service Value Chain interact?",
    options: [
      "They must always follow a rigid linear order from Plan to Deliver",
      "They can be combined in flexible sequences to form custom value streams",
      "They execute independently without sharing data",
      "They are executed only by external vendor management"
    ],
    correct: 1,
    explanation: "SVC activities are modular and combine dynamically to create specialized value streams."
  },
  {
    id: 66,
    category: "4. SVS & VALUE CHAIN",
    question: "Which component of the SVS refers to the means by which an organization is directed and controlled?",
    options: ["Governance", "Practices", "Service Value Chain", "Guiding Principles"],
    correct: 0,
    explanation: "Governance establishes organizational direction, compliance oversight, and control."
  },
  {
    id: 67,
    category: "4. SVS & VALUE CHAIN",
    question: "What is organizational agility within the Service Value System?",
    options: [
      "The ability to move all server workloads to cloud infrastructure",
      "The capacity of an organization to respond rapidly and effectively to change",
      "The practice of writing software without documentation",
      "The total elimination of change approval boards"
    ],
    correct: 1,
    explanation: "Agility allows organizations to adapt quickly to shifting demand and market conditions."
  },
  {
    id: 68,
    category: "4. SVS & VALUE CHAIN",
    question: "What is organizational resilience in the context of the SVS?",
    options: [
      "The ability to withstand, recover from, or adapt to disruptive changes",
      "The guarantee that no P1 incidents will occur",
      "The financial capacity to hire external consultants",
      "Maintaining legacy server hardware indefinitely"
    ],
    correct: 0,
    explanation: "Resilience ensures an organization can anticipate, withstand, and recover from operational shocks."
  },
  {
    id: 69,
    category: "4. SVS & VALUE CHAIN",
    question: "Which of these is NOT one of the 5 core components of the ITIL SVS?",
    options: [
      "ITIL Guiding Principles",
      "Governance",
      "Service Level Agreements",
      "Continual Improvement"
    ],
    correct: 2,
    explanation: "The 5 components of SVS are: Guiding Principles, Governance, Service Value Chain, Practices, and Continual Improvement. SLAs are practice artifacts."
  },
  {
    id: 70,
    category: "4. SVS & VALUE CHAIN",
    question: "What describes the journey from initial demand or opportunity to final value realization?",
    options: ["Service Level Pipeline", "Value Stream", "Change Control Log", "Incident Escalation Path"],
    correct: 1,
    explanation: "A value stream represents the specific pathway of SVC activities that fulfills demand and delivers value."
  },

  // ==========================================
  // 5. ITIL MANAGEMENT PRACTICES (71-100)
  // ==========================================
  {
    id: 71,
    category: "5. ITIL PRACTICES",
    question: "What is the primary purpose of the 'Incident Management' practice?",
    options: [
      "To reduce the likelihood and impact of incidents by identifying causes",
      "To restore normal service operation as quickly as possible",
      "To maximize the number of successful service changes",
      "To align business targets with service performance"
    ],
    correct: 1,
    explanation: "Incident Management focuses on rapid service restoration to minimize business disruption."
  },
  {
    id: 72,
    category: "5. ITIL PRACTICES",
    question: "How is an 'Incident' defined in ITIL 4?",
    options: [
      "A cause or potential cause of one or more unknown events",
      "An unplanned interruption to a service or reduction in service quality",
      "A pre-authorized low-risk modification to a system",
      "A state change that has significance for service management"
    ],
    correct: 1,
    explanation: "An incident is an unplanned service interruption or performance degradation."
  },
  {
    id: 73,
    category: "5. ITIL PRACTICES",
    question: "What is the primary goal of 'Problem Management'?",
    options: [
      "To answer user requests for password resets",
      "To reduce the likelihood and impact of incidents by identifying actual and potential causes",
      "To deploy software updates to production environments",
      "To manage third-party supplier contracts"
    ],
    correct: 1,
    explanation: "Problem Management analyzes root causes to prevent incident recurrence and manage workarounds."
  },
  {
    id: 74,
    category: "5. ITIL PRACTICES",
    question: "What is a 'Problem' in ITIL terms?",
    options: [
      "A service failure with an unknown resolution date",
      "A cause or potential cause of one or more incidents",
      "An unauthorized change to production infrastructure",
      "A breach of a Service Level Agreement"
    ],
    correct: 1,
    explanation: "A problem is the underlying cause (or potential cause) of incidents."
  },
  {
    id: 75,
    category: "5. ITIL PRACTICES",
    question: "What is a problem called once its root cause has been analyzed and a temporary resolution identified?",
    options: ["Incident Record", "Known Error", "Standard Change", "Service Request"],
    correct: 1,
    explanation: "A problem becomes a 'Known Error' once the cause is understood and a workaround or permanent fix is documented."
  },
  {
    id: 76,
    category: "5. ITIL PRACTICES",
    question: "What is a temporary solution that reduces or eliminates the impact of an incident or problem without resolving the root cause?",
    options: ["Patch", "Workaround", "Standard Change", "Baseline"],
    correct: 1,
    explanation: "A workaround temporarily restores service or mitigates impact while a permanent fix is researched."
  },
  {
    id: 77,
    category: "5. ITIL PRACTICES",
    question: "Which practice ensures that risks are properly assessed, authorizing changes to proceed while maximizing successful implementations?",
    options: ["Release Management", "Change Enablement", "Deployment Management", "Service Configuration Management"],
    correct: 1,
    explanation: "Change Enablement assesses risks and balances speed with stability when approving changes."
  },
  {
    id: 78,
    category: "5. ITIL PRACTICES",
    question: "Which type of change is low-risk, pre-authorized, and follows a established standard procedure?",
    options: ["Normal change", "Emergency change", "Standard change", "Major change"],
    correct: 2,
    explanation: "Standard changes are pre-approved, routine, low-risk procedural tasks."
  },
  {
    id: 79,
    category: "5. ITIL PRACTICES",
    question: "Which type of change must be implemented as soon as possible, often bypassing standard approval workflows to resolve a critical incident?",
    options: ["Normal change", "Emergency change", "Standard change", "Routine change"],
    correct: 1,
    explanation: "Emergency changes address critical service disruptions and require streamlined, rapid approval."
  },
  {
    id: 80,
    category: "5. ITIL PRACTICES",
    question: "What is the primary role of the 'Service Desk' practice?",
    options: [
      "To perform deep-level software code development",
      "To serve as the single point of contact between the service provider and all users",
      "To approve infrastructure budget allocations",
      "To negotiate contract terms with external vendors"
    ],
    correct: 1,
    explanation: "The Service Desk acts as the central point of contact for handling incidents, service requests, and communication."
  },
  {
    id: 81,
    category: "5. ITIL PRACTICES",
    question: "What is the primary focus of the 'Service Request Management' practice?",
    options: [
      "To resolve high-priority system crashes",
      "To handle predefined, user-initiated requests for services, access, or information",
      "To repair faulty physical network cables",
      "To conduct formal root cause analysis"
    ],
    correct: 1,
    explanation: "Service Request Management handles routine requests like password resets, software installations, or hardware requests."
  },
  {
    id: 82,
    category: "5. ITIL PRACTICES",
    question: "Which practice sets clear business-based targets for service performance and ensures service delivery is assessed against them?",
    options: ["Service Level Management", "Availability Management", "Capacity Management", "Continual Improvement"],
    correct: 0,
    explanation: "Service Level Management negotiates SLAs and monitors service performance against agreed expectations."
  },
  {
    id: 83,
    category: "5. ITIL PRACTICES",
    question: "What document specifies agreed service targets between a service provider and a customer?",
    options: ["Operational Level Agreement (OLA)", "Service Level Agreement (SLA)", "Underpinning Contract (UC)", "Continual Improvement Register (CIR)"],
    correct: 1,
    explanation: "An SLA is a formal agreement between a provider and customer defining target service metrics."
  },
  {
    id: 84,
    category: "5. ITIL PRACTICES",
    question: "Which practice continually aligns an organization's practices and services with changing business needs?",
    options: ["Continual Improvement", "Service Desk", "Incident Management", "Deployment Management"],
    correct: 0,
    explanation: "Continual Improvement drives ongoing enhancements across services, components, and practices."
  },
  {
    id: 85,
    category: "5. ITIL PRACTICES",
    question: "What database or document is used to track and manage improvement ideas across an organization?",
    options: ["Known Error Database (KEDB)", "Continual Improvement Register (CIR)", "Service Catalog", "Change Schedule"],
    correct: 1,
    explanation: "The CIR is used to log, prioritize, and track continuous improvement initiatives."
  },
  {
    id: 86,
    category: "5. ITIL PRACTICES",
    question: "Which practice ensures that accurate and reliable information about the configuration of services and CIs is available?",
    options: ["Service Asset Management", "Service Configuration Management", "Monitoring and Event Management", "Release Management"],
    correct: 1,
    explanation: "Service Configuration Management tracks Configuration Items (CIs) and their interrelationships."
  },
  {
    id: 87,
    category: "5. ITIL PRACTICES",
    question: "What is any component that needs to be managed in order to deliver an IT service called?",
    options: ["Asset", "Configuration Item (CI)", "Artifact", "Event"],
    correct: 1,
    explanation: "A Configuration Item (CI) is any hardware, software, network, or document managed to deliver a service."
  },
  {
    id: 88,
    category: "5. ITIL PRACTICES",
    question: "Which practice manages the financial value of IT assets across their operational lifecycle?",
    options: ["IT Asset Management", "Service Configuration Management", "Supplier Management", "Service Level Management"],
    correct: 0,
    explanation: "IT Asset Management tracks financial, contractual, and lifecycle data for hardware and software assets."
  },
  {
    id: 89,
    category: "5. ITIL PRACTICES",
    question: "Which practice makes new and changed services and features available for use?",
    options: ["Release Management", "Deployment Management", "Change Enablement", "Service Request Management"],
    correct: 0,
    explanation: "Release Management makes new or updated functions available to end users."
  },
  {
    id: 90,
    category: "5. ITIL PRACTICES",
    question: "Which practice moves new or changed hardware, software, or documentation to live production environments?",
    options: ["Release Management", "Deployment Management", "Change Enablement", "Incident Management"],
    correct: 1,
    explanation: "Deployment Management physically or logically moves components to production environments."
  },
  {
    id: 91,
    category: "5. ITIL PRACTICES",
    question: "Which practice systematically observes services and service components to record and report selected state changes?",
    options: ["Service Desk", "Monitoring and Event Management", "Incident Management", "Problem Management"],
    correct: 1,
    explanation: "Monitoring and Event Management detects, categorizes, and responds to state changes across systems."
  },
  {
    id: 92,
    category: "5. ITIL PRACTICES",
    question: "What is any change of state that has significance for the management of a service or other configuration item?",
    options: ["Incident", "Event", "Problem", "Alert"],
    correct: 1,
    explanation: "An event is a detectable state change recorded by infrastructure tools or application logs."
  },
  {
    id: 93,
    category: "5. ITIL PRACTICES",
    question: "Which practice protects information needed by the organization to conduct its business?",
    options: ["Information Security Management", "Relationship Management", "Supplier Management", "Service Level Management"],
    correct: 0,
    explanation: "Information Security Management maintains information confidentiality, integrity, and availability."
  },
  {
    id: 94,
    category: "5. ITIL PRACTICES",
    question: "Which practice establishes and nurtures links between an organization and its stakeholders at strategic and tactical levels?",
    options: ["Relationship Management", "Supplier Management", "Service Desk", "Change Enablement"],
    correct: 0,
    explanation: "Relationship Management identifies, analyzes, and improves bonds with internal and external stakeholders."
  },
  {
    id: 95,
    category: "5. ITIL PRACTICES",
    question: "Which practice ensures that an organization's suppliers and their performance are managed appropriately to support seamless service delivery?",
    options: ["Supplier Management", "Relationship Management", "Service Asset Management", "Service Level Management"],
    correct: 0,
    explanation: "Supplier Management negotiates contracts and evaluates vendor performance to ensure quality output."
  },
  {
    id: 96,
    category: "5. ITIL PRACTICES",
    question: "Which practice ensures services deliver agreed levels of availability to meet customer needs?",
    options: ["Availability Management", "Capacity and Performance Management", "Service Continuity Management", "Service Desk"],
    correct: 0,
    explanation: "Availability Management ensures services are operational and accessible when required."
  },
  {
    id: 97,
    category: "5. ITIL PRACTICES",
    question: "Which practice ensures services achieve agreed performance levels without exceeding resource constraints?",
    options: ["Capacity and Performance Management", "Availability Management", "Service Level Management", "IT Asset Management"],
    correct: 0,
    explanation: "Capacity and Performance Management ensures systems meet performance needs cost-effectively."
  },
  {
    id: 98,
    category: "5. ITIL PRACTICES",
    question: "What skill set is most crucial for Service Desk staff?",
    options: [
      "Deep technical command line expertise exclusively",
      "Customer service skills, empathy, communication, and problem resolution",
      "Database administration and SQL queries",
      "Contract negotiation and legal analysis"
    ],
    correct: 1,
    explanation: "While technical skills matter, soft skills—empathy, communication, customer care—are paramount on the Service Desk."
  },
  {
    id: 99,
    category: "5. ITIL PRACTICES",
    question: "What is an Operational Level Agreement (OLA)?",
    options: [
      "An agreement between a service provider and an external commercial vendor",
      "An agreement between an IT service provider and another part of the same organization",
      "A contract signed by end users accepting acceptable use policies",
      "A financial statement detailing IT infrastructure costs"
    ],
    correct: 1,
    explanation: "An OLA is an internal agreement between different departments within the same organization supporting SLA targets."
  },
  {
    id: 100,
    category: "5. ITIL PRACTICES",
    question: "Which practice handles major disruptions requiring business continuity plans to be activated?",
    options: ["Service Continuity Management", "Incident Management", "Problem Management", "Change Enablement"],
    correct: 0,
    explanation: "Service Continuity Management prepares organizations to maintain critical operations during major disaster events."
  }
];
